### PR TITLE
version 0.2.4: move scipy/matplotlib/skimage into sub-func

### PR DESCRIPTION
**Pull request by yunjunz**
+ move scipy/matplotlib/skimage into the sub-functions, to avoid adding them to the requirements/host in the conda-forge recipe, as the latter is recommended by conda-forge guideline

+ add release Tag for version 0.2.4

### CODE REVIEW

**Comment by jhkennedy** [comment]
@yunjunz where do you see this recommendation?

**Comment by yunjunz** [comment]
> @yunjunz where do you see this recommendation?

Hi @jhkennedy, I was reading from here (https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-host-and-run). My understanding from it is: `scipy/matplotlib-base/scikit-image` are supposed to be in `requirements/run`, but not recommended in the `requirements/host`, which was used during the building.

This is because of the change in `setup.py` in #40, where I use `import pysolid.version` to grab the version number. After that, the conda-forge feedstock testing failed due to the lack of the above 3 packages in https://github.com/conda-forge/pysolid-feedstock/pull/10.

**Comment by jhkennedy** [comment]
@yunjunz ah gotcha!

Generally, the recommendation is to *not* import your package in `setup.py` as your build and runtime requirements get mangled. 

I agree it's desirable to provide the version number as a package variable and dynamically generate the version from the git history for dev versions, but you can do that without needing to import the package using tools like [`setuptools_scm`](https://github.com/pypa/setuptools_scm). It would give you most of what you're doing in [`version.py`](https://github.com/insarlab/PySolid/blob/main/src/pysolid/version.py) for free. We're using it in the `hyp3_sdk` and a few other packages and have been really happy with it.

I could open a PR for that if you'd like.

**Comment by yunjunz** [comment]
That would be great @jhkennedy!

And you are also more than welcome to change `setup.py` to `setup.cfg` with `pyproject.toml`, if that makes your PR easier.

**Pull request merged**
